baseURL: "https://qqq.ninja/blog"
title: Quentin's blog
paginate: 12
languageCode: "en-us"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author: ["Quentin McGaw"]

  defaultTheme: "dark"
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: true

  homeInfoParams:
    Title: "Quentin's blog"
    Content: >
      ![Title](images/featured_image.jpg)
  socialIcons:
    - name: github
      url: "https://github.com/qdm12"
    - name: reddit
      url: https://reddit.com/u/dowitex
    - name: linkedin
      url: "https://www.linkedin.com/in/quentin-mcgaw/"
    - name: paypal
      url: https://paypal.me/qmcgaw
    - name: RsS
      url: "index.xml"
    - name: medium
      url: https://medium.com/@quentin.mcgaw/

  editPost:
    URL: "https://github.com/qdm12/blog/edit/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35
  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"
  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

taxonomies:
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
