name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yml
      - archetypes/**
      - content/**
      - data/**
      - layouts/**
      - resources/**
      - static/**
      - themes/**
      - .dockerignore
      - config.yml
      - Dockerfile
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - archetypes/**
      - content/**
      - data/**
      - layouts/**
      - resources/**
      - static/**
      - themes/**
      - .dockerignore
      - config.yml
      - Dockerfile

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Build final image
        run: docker build .

  publish:
    needs: [verify]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1.10.0
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=commit::$(git rev-parse --short HEAD)
          echo ::set-output name=created::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo ::set-output name=version::$TAG
            echo ::set-output name=platforms::linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          elif [ "$BRANCH" = "main" ]; then
            echo ::set-output name=version::latest
            echo ::set-output name=platforms::linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          else
            echo ::set-output name=version::$BRANCH
            echo ::set-output name=platforms::linux/amd64
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.vars.outputs.created }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
          tags: qmcgaw/blog:${{ steps.vars.outputs.version }}
          push: true
